### ISSUE TITLE
Code syntax highlighting

### ISSUE THREAD

**Issue by rounakdatta** [lingxz/er#17]
Hello lingxz,
Thanks for this amazing theme. I have managed to set up my blog publishing flow (emacs org roam -> ox-hugo -> er hugo compilation): https://rounakdatta.github.io/posts/open-source-tools-everyday/#what-i-type-is-what-you-see.

However, I have not managed to get code syntax highlighting correctly yet (tried https://gohugo.io/getting-started/configuration-markup#highlight as well). Do you have any pointers on how to set it up correctly?

**Comment by lingxz** [comment]
hmm, syntax highlighting works on the example site https://themes.gohugo.io//theme/er/post/markdown-syntax/, so it's probably something about your config. You're saying that even copying this config block https://gohugo.io/getting-started/configuration-markup#highlight into your config.toml also didn't work?

**Comment by rounakdatta** [comment]
Aha, sorry for bothering, I was using `pygmentsUseClasses = true` along with the chroma config. This was the reason why it was getting overriden. Thanks, I've solved it now :)
