### ISSUE TITLE
[Feature Request] Search

### ISSUE THREAD

**Issue by rootkea** [lingxz/er#6]
Hello!  

Search is one of the best and quickest way to browse any website. It would be really great if we could add the Search functionality in Er.  

I would like to request the search functionality based on any of the non-commercial search tools.[0] e.g. hugo-lunr, hugo-elasticsearch etc.  

Here[1] is the search functionality implemented by story theme using lunr.js[2]  

Thanks!  

[0] https://gohugo.io/tools/search/  
[1] https://themes.gohugo.io/theme/story/search/  
[2] https://github.com/olivernn/lunr.js

**Comment by lingxz** [comment]
Hi, thanks for your interest! I briefly considered adding search before, but I wanted to keep this theme lightweight, and personally I think adding search will deviate from that aim because quite some javascript will need to be added. But feel free to fork and add it yourself!
